
name: Cleanup Playwright Tests
on: 
  workflow_call:
    inputs:
      mailinator_private_domain:
        type: string
        description: 'Mailinator Private Domain'
        required: true
      auth0_domain:
        type: string
        description: 'Target Auth0 Domain'
        required: true
      auth0_e2e_client_id:
        type: string
        description: 'Auth0 Client ID of E2E tests'
        required: true
    secrets: 
      MAILINATOR_API_KEY: 
        required: true
      AUTH0_E2E_CLIENT_SECRET:
        required: true
jobs:
  cleanup:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Run cleanup script
      run: npm run cleanup
      env:
        MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
        MAILINATOR_PRIVATE_DOMAIN: ${{ inputs.mailinator_private_domain }}
        AUTH0_DOMAIN: ${{ inputs.auth0_domain }}
        AUTH0_E2E_CLIENT_ID: ${{ inputs.auth0_e2e_client_id }}
        AUTH0_E2E_CLIENT_SECRET: ${{ secrets.AUTH0_E2E_CLIENT_SECRET }}
