name: Run Playwright Tests
on: 
  workflow_call:
    inputs:
      ci:
        type: boolean
        default: false
      report_to_slack:
        type: boolean
        default: false
      target_url:
        type: string
        description: 'URL of the site to run E2E tests against'
        required: true
      mailinator_private_domain:
        type: string
        description: 'Mailinator Private Domain'
        required: true
      auth0_domain:
        type: string
        description: 'Target Auth0 Domain'
        required: true
      auth0_e2e_client_id:
        type: string
        description: 'Auth0 Client ID of E2E tests'
        required: true
    secrets: 
      MAILINATOR_API_KEY: 
        required: true
      AUTH0_E2E_CLIENT_SECRET:
        required: true
      SLACK_WEBHOOK_URL:
        required: false
jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
      env:
        CI: ${{ inputs.ci }}
        ACCOUNTS_DEMO_APP_URL: ${{ inputs.target_url }}
        MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
        MAILINATOR_PRIVATE_DOMAIN: ${{ inputs.mailinator_private_domain }}
        AUTH0_DOMAIN: ${{ inputs.auth0_domain }}
        AUTH0_E2E_CLIENT_ID: ${{ inputs.auth0_e2e_client_id }}
        AUTH0_E2E_CLIENT_SECRET: ${{ secrets.AUTH0_E2E_CLIENT_SECRET }}
    - name: Report failures to Slack
      if: failure() && ${{ inputs.report_to_slack }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: Account System E2E Tests
        SLACK_ICON_EMOJI: ':robot_face:'
        SLACK_COLOR: 'danger'
        SLACK_TITLE: 'E2E Test Run Failure'
        SLACK_MESSAGE: 'A failure has occurred while running the Account System E2E suite targeting ${{ inputs.target_url }}. Please inspect the GH Actions logs for more information.'
    