name: Run Tests
on: 
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
          description: 'Environment to run tests against'
          type: choice
          required: true
          options:
            - development
            - staging
            - production
          default: development
  schedule:
    - cron: '0 */1 * * *' # run every hour
    
jobs:
  # BEGIN - pull request to main CI runs (targets Dev)
  ci_test: 
    uses: ./.github/workflows/playwright.yml
    if: ${{ github.event_name == 'pull_request' }}
    with:
      ci: true
      target_url: https://account-system-auth0.dev-submittable.com/login
      mailinator_private_domain: submittable.testinator.com
      auth0_domain: account-system-dev.eu.auth0.com
      auth0_e2e_client_id: PEltKKABdFXRiMObmGZaZ0Gzt28q2lyJ
    secrets: 
      MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
      AUTH0_E2E_CLIENT_SECRET: ${{ secrets.AUTH0_E2E_CLIENT_SECRET_DEV }}
  # END - automated test runs on schedule

  # BEGIN - automated test runs on schedule (targets Prod)
  scheduled_test: 
    uses: ./.github/workflows/playwright.yml
    if: ${{ github.event_name == 'schedule' }}
    with:
      target_url: https://account-system-auth0.submittable.com/login
      mailinator_private_domain: submittable.testinator.com
      auth0_domain: account-system-prod.eu.auth0.com
      auth0_e2e_client_id: Wj5Ah6ALtFoeZFBtDdiDgyDDur3DH9nS
      report_to_slack: true
    secrets: 
      MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
      AUTH0_E2E_CLIENT_SECRET: ${{ secrets.AUTH0_E2E_CLIENT_SECRET_PROD }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  # END - automated test runs on schedule

  # BEGIN - manually triggered test runs
  dev_test:
    uses: ./.github/workflows/playwright.yml
    if: ${{ github.event.inputs.environment == 'development' }}
    with:
      target_url: https://account-system-auth0.dev-submittable.com/login
      mailinator_private_domain: submittable.testinator.com
      auth0_domain: account-system-dev.eu.auth0.com
      auth0_e2e_client_id: PEltKKABdFXRiMObmGZaZ0Gzt28q2lyJ
    secrets: 
      MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
      AUTH0_E2E_CLIENT_SECRET: ${{ secrets.AUTH0_E2E_CLIENT_SECRET_DEV }}

  stg_test:
    uses: ./.github/workflows/playwright.yml
    if: ${{ github.event.inputs.environment == 'staging' }}
    with:
      target_url: https://account-system-auth0.staging-submittable.com/login
      mailinator_private_domain: submittable.testinator.com
      auth0_domain: account-system-staging.eu.auth0.com
      auth0_e2e_client_id: 2ER0IDutTClZXWg0Rb0FGoQhpXpyH4ap
    secrets: 
      MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
      AUTH0_E2E_CLIENT_SECRET: ${{ secrets.AUTH0_E2E_CLIENT_SECRET_STG }}

  prod_test:
    uses: ./.github/workflows/playwright.yml
    if: ${{ github.event.inputs.environment == 'production' }}
    with:
      target_url: https://account-system-auth0.submittable.com/login
      mailinator_private_domain: submittable.testinator.com
      auth0_domain: account-system-prod.eu.auth0.com
      auth0_e2e_client_id: Wj5Ah6ALtFoeZFBtDdiDgyDDur3DH9nS
      report_to_slack: true
    secrets: 
      MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
      AUTH0_E2E_CLIENT_SECRET: ${{ secrets.AUTH0_E2E_CLIENT_SECRET_PROD }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  # END - manually triggered test runs

  # BEGIN - auto-cleanup jobs
  dev_cleanup:
    needs: dev_test
    if: always() && ${{ needs.dev_test.result == 'failure' }}
    uses: ./.github/workflows/cleanup.yml
    with:
      mailinator_private_domain: submittable.testinator.com
      auth0_domain: account-system-dev.eu.auth0.com
      auth0_e2e_client_id: PEltKKABdFXRiMObmGZaZ0Gzt28q2lyJ
    secrets:
      MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
      AUTH0_E2E_CLIENT_SECRET: ${{ secrets.AUTH0_E2E_CLIENT_SECRET_DEV }}

  stg_cleanup:
    needs: stg_test
    if: always() && ${{ needs.stg_test.result == 'failure' }}
    uses: ./.github/workflows/cleanup.yml
    with:
      mailinator_private_domain: submittable.testinator.com
      auth0_domain: account-system-staging.eu.auth0.com
      auth0_e2e_client_id: 2ER0IDutTClZXWg0Rb0FGoQhpXpyH4ap
    secrets:
      MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
      AUTH0_E2E_CLIENT_SECRET: ${{ secrets.AUTH0_E2E_CLIENT_SECRET_STG }}
    
  prod_cleanup:
    needs: [ prod_test, scheduled_test ]
    if: always() && ${{ needs.prod_test.result == 'failure' || needs.scheduled_test.result == 'failure' }}
    uses: ./.github/workflows/cleanup.yml
    with:
      mailinator_private_domain: submittable.testinator.com
      auth0_domain: account-system-prod.eu.auth0.com
      auth0_e2e_client_id: Wj5Ah6ALtFoeZFBtDdiDgyDDur3DH9nS
    secrets:
      MAILINATOR_API_KEY: ${{ secrets.MAILINATOR_API_KEY }}
      AUTH0_E2E_CLIENT_SECRET: ${{ secrets.AUTH0_E2E_CLIENT_SECRET_PROD }}
  # END - auto-cleanup jobs